spring:
  profiles:
    active: dev
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useSSL=false
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: updater
  devtools:
    restart:
      log-condition-evaluation-delta: true
  application:
    admin:
      enabled: true
  output:
    ansi:
      enabled: detect
  mvc:
    static-path-pattern: /**
logging:
  level:
    root: INFO
another:
#trace: true
#  name: qweasdzxc

