spring:
  data:
  profiles:
    active: dev
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useSSL=false
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update